name: NayefAlghamdi
favicon: null
layout_spectrum: 0.89689
typography_spectrum: 0.8174150306731462
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e5f1'
    - '#7480b2'
    - '#c1c0df'
    - '#040b01'
    - '#45412e'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
